language: objective-c

install:
  - npm install -g cordova
  - cordova create testing com.tester.test Tester
  - cd testing
  - cordova platform add ios

script:
  - cordova plugin add https://github.com/DavidBriglio/cordova-banner-notification
  - cordova build ios
